config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  mount ActionCable.server => '/cable'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'home', to: 'static_pages#show'
  get 'dashboard', to: 'dashboard#show', as: 'dashboard'
  get 'privacy', to: 'static_pages#privacy'

  root to: "static_pages#show"

  resources :moves
  resources :games do
    member do
      patch :join
      patch :forfeit
      patch :left_white_castle
    end
  end

  resources :pieces

end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord

  belongs_to :white_player, class_name: 'User', optional: true
  belongs_to :black_player, class_name: 'User', optional: true

  has_many :pieces
  has_many :users
  
  scope :available, -> { where(black_player: nil) }

  def unmatched_games
    Game.where(black_player: nil) && Game.where(white_player: !nil)
  end
  
  def in_play?
    self.white_id != nil && self.black_id != nil
  end

  def first_turn!
    update(user_turn: 'white')
  end

  def turn_user_validation
    if (user_turn == 'white') && (self.white_id == self.player_id) && (self.pieces.where(color: "white"))
      return 'white'
    elsif (user_turn == 'black') && (self.black_id == self.second_player_id) && (self.pieces.where(color: "black"))
      return 'black'
    end
  end

  def pass_turn!
    if (self.user_turn == 'white') 
      update(user_turn: 'black')
    elsif (self.user_turn == 'black')
      update(user_turn: 'white')
    end
  end

  def tile_taken?(x_path, y_path)
    pieces.where(x_coord: x_path, y_coord: y_path).first.present? 
  end 
  
  def in_check?(color)
    @rival_causing_check = []
    king = find_king(color)
    if king
      opponents = opponent_pieces(color)
      opponents.each do |piece|
        @rival_causing_check << piece if piece.valid_move?(king.x_coord, king.y_coord) == true
      end
    end
    return true if @rival_causing_check.any?
  end

  #validates :name, presence: true
  def set_up_board!
  # Pawns
    (0..7).each do |x_coord|
      Pawn.create(game_id: id, color: "white", x_coord: x_coord, y_coord: 6, name: "White_Pawn", title: "Pawn")
    end

    (0..7).each do |x_coord|
      Pawn.create(game_id: id, color: "black", x_coord: x_coord, y_coord: 1, name: "Black_Pawn", title: "Pawn" )
    end

    # Rooks
    [0, 7].each do |x_coord|
      Rook.create(game_id: id, color: "white", x_coord: x_coord, y_coord: 7,  name: "White_Rook", title: "Rook")
    end

    [0, 7].each do |x_coord|
      Rook.create(game_id: id, color: "black", x_coord: x_coord, y_coord: 0, name: "Black_Rook", title: "Rook")
    end

    # Knights
    [1, 6].each do |x_coord|
      Knight.create(game_id: id, color: "white", x_coord: x_coord, y_coord: 7, name: "White_Knight", title: "Knight")
    end

    [1, 6].each do |x_coord|
      Knight.create(game_id: id, color: "black", x_coord: x_coord, y_coord: 0, name: "Black_Knight",  title: "Knight")
    end

    #Bishops
    [2, 5].each do |x_coord|
      Bishop.create(game_id: id, color: "white", x_coord: x_coord, y_coord: 7, name: "White_Bishop", title: "Bishop")
    end

    [2, 5].each do |x_coord|
      Bishop.create(game_id: id, color: "black", x_coord: x_coord, y_coord: 0, name: "Black_Bishop", title: "Bishop")
    end

    #Kings
    King.create(game_id: id, color: "white", x_coord: 4, y_coord: 7, name: "White_King", title: "King")


    King.create(game_id: id, color: "black", x_coord: 4, y_coord: 0, name: "Black_King", title: "King")

    #Queens
    Queen.create(game_id: id, color: "white", x_coord: 3, y_coord: 7, name: "White_Queen",  title: "Queen")

    Queen.create(game_id: id, color: "black", x_coord: 3, y_coord: 0,  name: "Black_Queen",  title: "Queen")
  
  def opponent_pieces(color)
    rival_color = if color == 'black'
      'white'
    else
      'black'
    end
    pieces.where(color: rival_color).to_a
  end

  def my_pieces(color)
    friendly_pieces = if color == 'black'
      'black'
    else
      'white'
    end
    pieces.where(color: friendly_pieces).to_a
  end

  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  attr_accessor :king_black, :king_white, :right_rook_black, :left_rook_black, :right_rook_black, :left_rook_white
  before_action :authenticate_user!
  
  def new
    @game = Game.new
  end

  def create
    @game = current_user.games.create(player_id: current_user.id, white_id: current_user.id, name: game_params["name"])
    @game.save
    @game.set_up_board!
    @game.first_turn!
    redirect_to game_path(@game)
  end

  def show
    @game = Game.find_by_id(params[:id])
    @pieces = @game.pieces
    @user = @game.users
  end

  def index
    @unmatched_games = Game.where(:white_id => nil).where.not(:black_id => nil).or (Game.where.not(:white_id => nil).where(:black_id => nil))
  end

  def join
    @game = Game.find_by_id(params[:id])
    @game.update(black_id: current_user.id, second_player_id: current_user.id)
    redirect_to game_path(@game)
  end
  
   def forfeit
    @game = Game.find_by_id(params[:id])
    if current_user.id == @game.white_id
      @game.update_attributes(winner: @game.black_id, loser: @game.white_id)
    else
      @game.update_attributes(winner: @game.white_id, loser: @game.black_id)
    end
    redirect_to games_path
  end

  def destroy
    @game = Game.find_by_id(params[:id])
    if @game.in_play?
      return render plain: "Not Allowed", status: :forbidden
    else
      @game.pieces.destroy_all
      @game.destroy
      redirect_to games_path
    end
  end

  private

  def game_params
    params.require(:game).permit(:player_id, :second_player_id, :user_id, :name, :white_id, :black_id, :winner, :loser, :user_turn)
  end
end

app/helpers/games_helper.rb
# frozen_string_literal: true

module GamesHelper
end

app/views/games/_form.html.erb
<%= simple_form_for(@game) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb

<br />
<section class="col-12 box">
  <h1> Available Games </h1>
    <% if @unmatched_games.present? %>
      <% @unmatched_games.each do |game| %>
        <h5 class="text-center"><%= "Game #{game.id}" %></h5>
        <% if game.white_id.blank? %>
          <%= simple_form_for game, url: join_game_path(game) do |f| %>
            <%= f.input :white_id, as: :hidden, :input_html => { :value => current_user.id } %>
            <%= f.submit "Join as white player", class: "btn btn-secondary" %>
          <% end %>       
        <% else %>
          <%= simple_form_for game, url: join_game_path(game) do |f| %>
            <%= f.input :black_id, as: :hidden, :input_html => { :value => current_user.id } %>
            <%= f.submit "Join as black player", class: "btn btn-secondary" %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
    <br class="clear">
</section>
            

app/views/games/new.html.erb
   <br />
   <section class="col-12 box">
    <h1>Create a Game</h1>
    <%= simple_form_for @game do |f| %>
      <%= f.input   :name %>
      <%= f.input   :white_id, as: :hidden, :input_html => { :value => current_user.id } %>
      <br />
      <%= f.button  :submit, class: 'btn btn-secondary' %>
    <% end %>
    <br class="clear" />
    </section>

app/views/games/show.html.erb
<head>
    <meta name="viewport" content="width=device-width, initial-scale=0.86, maximum-scale=3.0, minimum-scale=0.86">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>

<body>
<section>
  <div class="game" data-game-id=<%= @game.id %>>
    <h1 class="text-center">
        
    </h1>
    <br />
    <div class="rotate">
      <table class="show-topper">
          <tr>
              <td class="left">
               <div class="captured_pieces" style="float-left">
                <a href="#" data-toggle="capture-instructions" title="You may need to scroll to see all the pieces."><p>Captured Pieces</p></a>
                  <% @game.pieces.where(captured: true, color: "white").each do |piece| %>
                    <span class="captured_piece white_taken"><%= piece.unicode_symbol.html_safe %></span>
                  <% end %>
                  <br />
                  <% @game.pieces.where(captured: true, color: 'black').each do |piece| %>
                    <span class="captured_piece black_taken"><%= piece.unicode_symbol.html_safe %></span>
                  <% end %>
                </div>
              </td>
              <td>
              <h1 class="game-box"><%= @game.name %></h1>
              </td>
              <td class=right>
              <br />
                <p class="rotate-board" id="Flip_Board">Flip</p>
              </td>
          </tr>
      </table>
  </div>
  <div class="set-board">
    <div class="chess" align="center">
        <div class="board">
          <table>
            <% (0..7).each do |y_coord| %>
              <% (0..7).each do |x_coord| %>
                <td data-x-coord=<%=x_coord %> data-y-coord=
                    <%= y_coord %> class='tile
                    <%= "#{(y_coord.odd? == x_coord.odd? ? "white-tile droppable-tile" : "black-tile droppable-tile")}" %>'>
                    <% if board_piece = @pieces.select{|p| p.x_coord == x_coord && p.y_coord == y_coord}.first %>
                      <div title="<%= board_piece.title %>" class="piece <%=board_piece.color %>" data-piece-id=
                        <%= board_piece.id %> data-x_coord=
                        <%= x_coord %> data-y_coord=
                        <%= y_coord %> data-piece-id=
                        <%= board_piece.id %> data-name=
                        <%= board_piece.name %>>
                          <%= board_piece.unicode_symbol.html_safe %>
                          <% if (board_piece.name == "White_Pawn" && board_piece.y_coord == 0) || (board_piece.name == "Black_Pawn" && board_piece.y_coord == 7) %>
                          <% board_piece.update(promotion?: true) %>
                            <span class="promote">
                              <%= link_to "Promote", edit_piece_path(board_piece.id.to_s) %>
                            </span>
                            <% @game.reload %>
                          <% end %>
                      </div>
                    <% end %>
                </td>
              <% end %>
              </tr>
            <% end %>
        </table>
      </div>
      <div id="labels">
        <table class="y_labels">
            <% for i in 8.downto(1) %>
              <td>
                <div class="label_square">
                    <%= i %>
                </div>
            </td>
            </tr>
          <% end %>
        </table>
      </div>
      <div id="labels">
          <table class="x_labels">
              <tr>
                <% x_labels = { 0 => 'A', 1 => 'B', 2 => 'C', 3 => 'D', 4 => 'E', 5 => 'F', 6 => 'G', 7 => 'H' } %>
                <% for i in 0..7 %>
                  <td>
                    <div class="letters">
                        <%= x_labels[i].reverse %>
                    </div>
                  </td>
                <% end %>
              </tr>
          </table>
          <br />
      </div>
    </div>
</section>
<% if @game.in_play? %>
  <div class="float-left user_turn">
  <% if @game.user_turn == 'black'%>
    <center><span class="wlack_turn"><%= "It is" %><br /><%= "#{@game.user_turn.capitalize}'s turn." %></span></center>
  <% else %>
    <center><span class="white_turn"><%= "It is"%><br /><%= "#{@game.user_turn.capitalize}'s turn." %></span></center>
  <% end %>
  </div>
<% end %>
<br /><br /><br />
<div id="forfeit">
  <% if @game.in_play? %>
    <%= simple_form_for @game, url: forfeit_game_path(@game) do |f| %>
      <% if current_user.id == @game.white_id %>
        <%= f.input :winner, as: :hidden, :input_html => { :value => @game.black_id } %>
        <%= f.input :loser, as: :hidden, :input_html => { :value => @game.white_id } %>
      <% else %>
        <%= f.input :winner, as: :hidden, :input_html => { :value => @game.white_id } %>
        <%= f.input :loser, as: :hidden, :input_html => { :value => @game.black_id } %>
      <% end %>
      <%= f.submit "Forfeit", class: "forfeit", data: { confirm: "Are you sure you want to concede the game?"} %>
    <% end %>
  <% else %>
    <%= link_to 'Back', game_path(@game), method: :delete, class: 'btn btn-danger back', data: { confirm: "If you do this, the game will end before it begins. Are you sure?" } %>
  <% end %>
</div>
<script>
  setTimeout(function () { location.reload(1); }, 8000);
  var rotation = 0;
  jQuery.fn.rotate = function (degrees) {
    $(this).css({
      '-webkit-transform': 'rotate(' + degrees + 'deg)',
      '-moz-transform': 'rotate(' + degrees + 'deg)',
      '-ms-transform': 'rotate(' + degrees + 'deg)',
      'transform': 'rotate(' + degrees + 'deg)'
    });
  };
  $('#Flip_Board').click(function () {
    rotation -= 180;
    $('.set-board, .chess td, #labels td').rotate(rotation);
  });
  </script>  
</body>