config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  mount ActionCable.server => '/cable'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'home', to: 'static_pages#show'
  get 'dashboard', to: 'dashboard#show', as: 'dashboard'
  get 'privacy', to: 'static_pages#privacy'

  root to: "static_pages#show"

  resources :moves
  resources :games do
    member do
      patch :join
      patch :forfeit
      patch :left_white_castle
    end
  end

  resources :pieces

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chesster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #93847E;">
  <%= link_to root_path, class:'navbar-brand' do %>
  Chesster
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
          Games 
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="vertical-align:middle;">
          <%= link_to new_game_path, class: 'dropdown-item' do %>
          Create a Game
          <% end %>
          <div class="dropdown-divider"></div>
          <%= link_to games_path, class: 'dropdown-item' do %>
          Join a Game
          <% end %>
        </div>
      </li>
      <% if current_user %>
        <li class="nav-item">
          <%= link_to dashboard_path, class: 'nav-link' do %> 
            Dashboard
          <% end %>`
        </li>
      <% end %>
    </ul>
     <ul class="navbar-nav ml-auto">
      <% if current_user %>
        <%= link_to'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger btn-sm logout' %>
      <% else %>
        <li class="nav-item">
          <%= link_to user_session, class: 'btn btn-success' do %> 
            Sign in
          <% end %>`
        </li>
      <% end %>
        <li class="nav-item"> 
        <center><a class="git-link" title="Project GitHub Page" target="_blank" href="https://github.com/Toronto-s-Optimistic-Agile-Developers/Chesster"><i class="fa fa-github"></i></a></center>
      </li>
    </ul>
  </div>
</nav>
    <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
    <% elsif alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>